(feat)chaos-charts: adding chaosengine yamls
litmuschaos/chaos-charts pull request #131
Opened 2020-01-29 10:21 UTC by aditya109

Signed-off-by: aditya109 <adikid1996@gmail.com>

- added chaosengine for all the experiments

Solves : [1124](https://github.com/litmuschaos/litmus/issues/1124)

2020-01-29 11:06 UTC, ispeakc0de requested changes

2020-01-29 11:06 UTC, shubhamchaudhary commented on charts/coredns/coredns-pod-delete/engine.yaml
> +    appns: kube-system
Can you please add single quotes also for  `appns`, `appkind` and `jobCleanUpPolicy` in all files

2020-01-29 15:03 UTC, ispeakc0de requested changes

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-container-failure/engine.yaml
> +              value: deployment
single quotes missing

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-pod-failure/engine.yaml
> +              value: deployment
same as above

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-target-container-failure/engine.yaml
> +              value: deployment
same as above

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-target-network-delay/engine.yaml
> +              value: deployment
same as above

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-target-network-loss/engine.yaml
> +              value: deployment
same as above

2020-01-29 15:03 UTC, shubhamchaudhary commented on charts/openebs/openebs-target-pod-failure/engine.yaml
> +              value: deployment
same as above

2020-01-29 18:24 UTC, ispeakc0de requested changes

2020-01-29 18:24 UTC, shubhamchaudhary commented on charts/generic/pod-network-corruption/engine.yaml
> +              value: eth0
missing quotes

2020-01-30 05:29 UTC, amitbhatt818 requested changes

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/generic/node-drain/engine.yaml
> +  jobCleanUpPolicy: 'delete'
replace `infra` to `retain`

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-container-failure/engine.yaml
> +  jobCleanUpPolicy: 'delete'
same as above

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-pod-failure/engine.yaml
> +  # It can be delete/infra
Here also replace infra to retain

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/openebs/openebs-target-container-failure/engine.yaml
> +  # It can be delete/infra
same as above

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/openebs/openebs-target-network-delay/engine.yaml
> +  # It can be delete/infra
same as above

2020-01-30 05:29 UTC, amitbhatt818 commented on charts/openebs/openebs-target-pod-failure/engine.yaml
> +  # It can be delete/infra
same as above

2020-01-30 06:09 UTC, amitbhatt818 approved these changes
/lgtm

2020-01-30 06:58 UTC, ispeakc0de approved these changes
/lgtm

2020-01-30 07:02 UTC, chandankumar4 approved these changes

2020-01-30 07:03 UTC, merged