(WIP-feat): Adding Openebs pool network loss chart
litmuschaos/chaos-charts pull request #134
Opened 2020-02-06 17:51 UTC by rajdas98

- Adding Openebs pool network loss chart

2020-02-07 14:44 UTC, ksatchit commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +    applabel: 'app=busybox'
nginx stateful app

2020-02-07 14:44 UTC, ksatchit commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +            - name: FORCE
force not applicable

2020-02-07 14:45 UTC, ksatchit commented on charts/openebs/openebs-pool-network-loss/experiment.yaml
> +    - name: DATA_PERSISTENCE
recommended to set empty

2020-02-07 15:31 UTC, ispeakc0de requested changes

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +  namespace: openebs
default

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +  # It can be delete/retain
Can you please put this comment just before jobCleanUpPolicy

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +  chaosServiceAccount: pool-sa
nginx-sa

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +    appns: 'openebs'
default

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +            - name: APP_NAMESPACE
not applicable we are already getting this from `appinfo.appns`

2020-02-07 15:31 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-loss/engine.yaml
> +              value: ''
same as above

2020-02-07 15:36 UTC, shubhamchaudhary commented
Can you please add both charts (pool network loss/delay) (chart->openebs->openebs.package.yaml)[https://github.com/litmuschaos/chaos-charts/blob/master/charts/openebs/openebs.package.yaml] and (chart->openebs->openebs.chartserviceversion.yaml)[https://github.com/litmuschaos/chaos-charts/blob/master/charts/openebs/openebs.chartserviceversion.yaml] Files

2020-02-14 11:22 UTC, rajdas98 commented
ansible-playbook 2.7.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
statically imported: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml

2020-02-14 11:07:53.348540 PLAYBOOK: openebs_pool_network_loss_ansible_logic.yml 
1 plays in ./experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml

2020-02-14 11:07:53.551042 ************ BRACE YOURSELF, EXPERIMENT BEGINS! ************ 

2020-02-14 11:08:06.730184 Step: Gathering Facts 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml:1
META: ran handlers
included: /utils/runtime/create_testname.yml for 127.0.0.1
included: /utils/apps/openebs/fetch_sc_and_provisioner.yml for 127.0.0.1

2020-02-14 11:08:10.211840 Step: Identify the storage class used by the PVC 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:2
details => {"changed": true, "cmd": "kubectl get pvc testclaim -n openebs --no-headers -o custom-columns=:spec.storageClassName", "delta": "0:00:02.189529", "end": "2020-02-14 11:08:10.132470", "rc": 0, "start": "2020-02-14 11:08:07.942941", "stderr": "", "stderr_lines": [], "stdout": "openebs-standard", "stdout_lines": ["openebs-standard"]}

2020-02-14 11:08:12.453788 Step: Identify the storage provisioner used by the SC 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:10
details => {"changed": true, "cmd": "kubectl get sc openebs-standard --no-headers -o custom-columns=:provisioner", "delta": "0:00:01.763657", "end": "2020-02-14 11:08:12.391841", "rc": 0, "start": "2020-02-14 11:08:10.628184", "stderr": "", "stderr_lines": [], "stdout": "openebs.io/provisioner-iscsi", "stdout_lines": ["openebs.io/provisioner-iscsi"]}

2020-02-14 11:08:12.677447 Step: Record the storage class name 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:18
details => {"ansible_facts": {"sc": "openebs-standard"}, "changed": false}

2020-02-14 11:08:12.756430 Step: Record the storage provisioner name 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:22
details => {"ansible_facts": {"stg_prov": "openebs.io/provisioner-iscsi"}, "changed": false}

2020-02-14 11:08:15.205163 Step: Derive PV name from PVC to query storage engine type (openebs) 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:6
details => {"changed": true, "cmd": "kubectl get pvc testclaim -n openebs --no-headers -o custom-columns=:spec.volumeName", "delta": "0:00:01.982408", "end": "2020-02-14 11:08:15.113989", "rc": 0, "start": "2020-02-14 11:08:13.131581", "stderr": "", "stderr_lines": [], "stdout": "pvc-1da430ea-4f05-11ea-9072-42010a800120", "stdout_lines": ["pvc-1da430ea-4f05-11ea-9072-42010a800120"]}

2020-02-14 11:08:15.341363 Step: Record pv name 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:14
details => {"ansible_facts": {"pv_name": "pvc-1da430ea-4f05-11ea-9072-42010a800120"}, "changed": false}

2020-02-14 11:08:18.010780 Step: Check for presence & value of cas type annotation 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:18
details => {"changed": true, "cmd": "kubectl get pv pvc-1da430ea-4f05-11ea-9072-42010a800120 --no-headers -o jsonpath=\"{.metadata.annotations.openebs\\\\.io/cas-type}\"", "delta": "0:00:02.100218", "end": "2020-02-14 11:08:17.933068", "rc": 0, "start": "2020-02-14 11:08:15.832850", "stderr": "", "stderr_lines": [], "stdout": "cstor", "stdout_lines": ["cstor"]}

2020-02-14 11:08:18.245702 Step: Record the storage engine name 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:26
details => {"ansible_facts": {"stg_engine": "cstor"}, "changed": false}

2020-02-14 11:08:19.724656 Step: Identify the chaos util to be invoked 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:32
details => {"changed": true, "checksum": "d827b20e216f302a4e421e5d16fc5e5f41c70cec", "dest": "./chaosutil.yml", "gid": 0, "group": "root", "md5sum": "5428900aebe0864cf626207e6ead3db0", "mode": "0644", "owner": "root", "size": 127, "src": "/root/.ansible/tmp/ansible-tmp-1581678498.44-157015352279656/source", "state": "file", "uid": 0}

2020-02-14 11:08:20.744727 Step: Identify the data consistency util to be invoked 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:37
details => {"changed": true, "checksum": "6b3736a82fae08919391a13507b5f0f3a469df4f", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "32ffc4ed83920d5c9a3865d155926066", "mode": "0644", "owner": "root", "size": 124, "src": "/root/.ansible/tmp/ansible-tmp-1581678500.05-43921127918307/source", "state": "file", "uid": 0}

2020-02-14 11:08:20.945919 Step: Including chaos util for running the experiment 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:42
details => {"ansible_facts": {"c_util": "/experiments/openebs/openebs-pool-network-loss/cstor_pool_network_loss.yml"}, "ansible_included_var_files": ["/experiments/openebs/openebs-pool-network-loss/chaosutil.yml"], "changed": false}

2020-02-14 11:08:21.036091 Step: Including data persistence util to check data persistency 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml:46
details => {"ansible_facts": {"consistencyutil": "/utils/apps/mysql/mysql_data_persistence.yml"}, "ansible_included_var_files": ["/experiments/openebs/openebs-pool-network-loss/data_persistence.yml"], "changed": false}

2020-02-14 11:08:21.140358 Step: Construct chaos result name (experiment_name) 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml:32
details => {"ansible_facts": {"c_experiment": "pool-chaos-openebs-pool-network-loss"}, "changed": false}
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

2020-02-14 11:08:22.337339 Step: Generate the chaos result CR to reflect SOT (Start of Test) 
task path: /utils/runtime/update_chaos_result_resource.yml:3
details => {"changed": true, "checksum": "7b576ffd9c6194690fddffe3524f07945ab097a7", "dest": "./chaos-result.yml", "gid": 0, "group": "root", "md5sum": "15884e05665754520ec2610e1a1df1a5", "mode": "0644", "owner": "root", "size": 332, "src": "/root/.ansible/tmp/ansible-tmp-1581678501.54-267344728318938/source", "state": "file", "uid": 0}

2020-02-14 11:08:24.874214 Step: Apply the chaos result CR 
task path: /utils/runtime/update_chaos_result_resource.yml:13
details => {"changed": true, "cmd": "kubectl apply -f chaos-result.yml -n openebs", "delta": "0:00:01.989770", "end": "2020-02-14 11:08:24.842102", "failed_when_result": false, "rc": 0, "start": "2020-02-14 11:08:22.852332", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/pool-chaos-openebs-pool-network-loss configured", "stdout_lines": ["chaosresult.litmuschaos.io/pool-chaos-openebs-pool-network-loss configured"]}

2020-02-14 11:08:25.095173 Step: Display the app information passed via the test job 
task path: /experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml:44
details => {
    "msg": [
        "The appl [...]

2020-02-14 16:55 UTC, ispeakc0de approved these changes
/lgtm

2020-02-14 16:55 UTC, ksatchit approved these changes

2020-02-14 16:56 UTC, merged