(feat): Adding Openebs pool network delay chart
litmuschaos/chaos-charts pull request #135
Opened 2020-02-07 14:06 UTC by rajdas98

- Adding Openebs pool network delay chart

2020-02-07 14:29 UTC, ksatchit commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +    applabel: 'app=busybox'
we are using nginx as a stateful example in other openebs experiments

2020-02-07 14:30 UTC, ksatchit commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +  chaosServiceAccount: pool-sa
nginx-sa?

2020-02-07 14:30 UTC, ksatchit commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +            - name: FORCE
network delay doesn't use this ENV right?

2020-02-07 14:43 UTC, ksatchit reviewed
suggested changes

2020-02-07 15:24 UTC, ispeakc0de requested changes

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +  namespace: openebs
In all experiments, we are using `default` namespace. Can you pls put the same to maintain the uniformity.

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +  # It can be delete/retain
Can you please put this comment just before `jobCleanUpPolicy`

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +            - name: APP_NAMESPACE
We are getting this variable from `appinfo.appns`

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +            - name: APP_LABEL
We are getting this variable from appinfo.applabel

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +          - "persistentvolumeclaims"
It is present twice in this list

2020-02-07 15:24 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +      value: 'busybox'
Can you put it blank? If you want you can put a comment stating that It supports mysql and busybox both

2020-02-07 15:27 UTC, shubhamchaudhary commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +    appns: 'openebs'
default

2020-02-07 18:52 UTC, amitbhatt818 requested changes

2020-02-07 18:52 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/engine.yaml
> +  chaosType: 'infra'
@rajdas98  Can you please remove this line and add 
`# It can be true/false`
  `annotationCheck: 'false'`

2020-02-07 18:52 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +      value: '60000' # in milliseconds
Comment should come just above the line.

2020-02-07 18:52 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +      value: '60000' # in milliseconds
same here also

2020-02-07 18:52 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +      value: '1000' # in milliseconds
same here also

2020-02-07 18:52 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/openebs-pool-network-delay.chartserviceversion.yaml
> +     Network delay to pool pod belonging to a OpenEBS PVC
Add few more lines in description

2020-02-07 19:06 UTC, amitbhatt818 requested changes

2020-02-07 19:06 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/experiment.yaml
> +          - "update"
verbs should be in CRUD order.

2020-02-07 19:06 UTC, amitbhatt818 commented on charts/openebs/openebs-pool-network-delay/openebs-pool-network-delay.chartserviceversion.yaml
> +  chaosType: infra
Remove this line

2020-02-14 13:56 UTC, rajdas98 commented
```
ansible-playbook 2.7.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

2020-02-14 13:48:39.778591 PLAYBOOK: openebs_pool_network_delay_ansible_logic.yml 
1 plays in ./experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml

2020-02-14 13:48:39.801761 ************ BRACE YOURSELF, EXPERIMENT BEGINS! ************ 

2020-02-14 13:48:53.248010 Step: Gathering Facts 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml:1
META: ran handlers
included: /utils/runtime/create_testname.yml for 127.0.0.1
included: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml for 127.0.0.1
included: /utils/apps/openebs/fetch_sc_and_provisioner.yml for 127.0.0.1

2020-02-14 13:48:57.088310 Step: Identify the storage class used by the PVC 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:2
details => {"changed": true, "cmd": "kubectl get pvc demo-vol1-claim -n openebs --no-headers -o custom-columns=:spec.storageClassName", "delta": "0:00:02.410527", "end": "2020-02-14 13:48:57.055299", "rc": 0, "start": "2020-02-14 13:48:54.644772", "stderr": "", "stderr_lines": [], "stdout": "openebs-standard", "stdout_lines": ["openebs-standard"]}

2020-02-14 13:48:59.315817 Step: Identify the storage provisioner used by the SC 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:10
details => {"changed": true, "cmd": "kubectl get sc openebs-standard --no-headers -o custom-columns=:provisioner", "delta": "0:00:01.122045", "end": "2020-02-14 13:48:59.230461", "rc": 0, "start": "2020-02-14 13:48:58.108416", "stderr": "", "stderr_lines": [], "stdout": "openebs.io/provisioner-iscsi", "stdout_lines": ["openebs.io/provisioner-iscsi"]}

2020-02-14 13:48:59.529869 Step: Record the storage class name 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:18
details => {"ansible_facts": {"sc": "openebs-standard"}, "changed": false}

2020-02-14 13:48:59.665827 Step: Record the storage provisioner name 
task path: /utils/apps/openebs/fetch_sc_and_provisioner.yml:22
details => {"ansible_facts": {"stg_prov": "openebs.io/provisioner-iscsi"}, "changed": false}

2020-02-14 13:49:02.180038 Step: Derive PV name from PVC to query storage engine type (openebs) 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:6
details => {"changed": true, "cmd": "kubectl get pvc demo-vol1-claim -n openebs --no-headers -o custom-columns=:spec.volumeName", "delta": "0:00:01.945072", "end": "2020-02-14 13:49:02.042549", "rc": 0, "start": "2020-02-14 13:49:00.097477", "stderr": "", "stderr_lines": [], "stdout": "pvc-92656f0c-4f00-11ea-9072-42010a800120", "stdout_lines": ["pvc-92656f0c-4f00-11ea-9072-42010a800120"]}

2020-02-14 13:49:04.034933 Step: Check for presence & value of cas type annotation 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:14
details => {"changed": true, "cmd": "kubectl get pv pvc-92656f0c-4f00-11ea-9072-42010a800120 --no-headers -o jsonpath=\"{.metadata.annotations.openebs\\\\.io/cas-type}\"", "delta": "0:00:01.543297", "end": "2020-02-14 13:49:03.948797", "rc": 0, "start": "2020-02-14 13:49:02.405500", "stderr": "", "stderr_lines": [], "stdout": "cstor", "stdout_lines": ["cstor"]}

2020-02-14 13:49:04.231244 Step: Record the storage engine name 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:22
details => {"ansible_facts": {"stg_engine": "cstor"}, "changed": false}

2020-02-14 13:49:05.807210 Step: Identify the chaos util to be invoked 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:28
details => {"changed": true, "checksum": "8e3a3a452f31cb944f15b84615035112721f9615", "dest": "./chaosutil.yml", "gid": 0, "group": "root", "md5sum": "7cada6b687f17495e7bb9d91b5cc9904", "mode": "0644", "owner": "root", "size": 129, "src": "/root/.ansible/tmp/ansible-tmp-1581688144.37-265697521551981/source", "state": "file", "uid": 0}

2020-02-14 13:49:07.017819 Step: Identify the data consistency util to be invoked 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:33
details => {"changed": true, "checksum": "6b3736a82fae08919391a13507b5f0f3a469df4f", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "32ffc4ed83920d5c9a3865d155926066", "mode": "0644", "owner": "root", "size": 124, "src": "/root/.ansible/tmp/ansible-tmp-1581688145.94-226816062243285/source", "state": "file", "uid": 0}

2020-02-14 13:49:07.191815 Step: Including chaos util for running the experiment 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:38
details => {"ansible_facts": {"c_util": "/experiments/openebs/openebs-pool-network-delay/cstor_pool_network_delay.yml"}, "ansible_included_var_files": ["/experiments/openebs/openebs-pool-network-delay/chaosutil.yml"], "changed": false}

2020-02-14 13:49:07.268876 Step: Including data persistence util to check data persistency 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml:42
details => {"ansible_facts": {"consistencyutil": "/utils/apps/mysql/mysql_data_persistence.yml"}, "ansible_included_var_files": ["/experiments/openebs/openebs-pool-network-delay/data_persistence.yml"], "changed": false}

2020-02-14 13:49:07.406554 Step: Construct chaos result name (experiment_name) 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml:32
details => {"ansible_facts": {"c_experiment": "pool-chaos-openebs-pool-network-delay"}, "changed": false}
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

2020-02-14 13:49:08.445178 Step: Generate the chaos result CR to reflect SOT (Start of Test) 
task path: /utils/runtime/update_chaos_result_resource.yml:3
details => {"changed": true, "checksum": "d94a821a56af25d2d32833fa601aa65a8d6a1ed5", "dest": "./chaos-result.yml", "gid": 0, "group": "root", "md5sum": "5470c59573ebb672f1606f191c8dda91", "mode": "0644", "owner": "root", "size": 333, "src": "/root/.ansible/tmp/ansible-tmp-1581688147.65-188171194938959/source", "state": "file", "uid": 0}

2020-02-14 13:49:11.312210 Step: Apply the chaos result CR 
task path: /utils/runtime/update_chaos_result_resource.yml:13
details => {"changed": true, "cmd": "kubectl apply -f chaos-result.yml -n openebs", "delta": "0:00:02.228281", "end": "2020-02-14 13:49:11.247214", "failed_when_result": false, "rc": 0, "start": "2020-02-14 13:49:09.018933", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/pool-chaos-openebs-pool-network-delay configured", "stdout_lines": ["chaosresult.litmuschaos.io/pool-chaos-openebs-pool-network-delay configured"]}

2020-02-14 13:49:12.013916 Step: Display the app information passed via the test job 
task path: /experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml:44
details => {
    "msg": [
        "The application info is as follows:", 
        "Namespace    : openebs", 
        "Label        : lkey=lvalue", 
        "PVC          : demo-vol1-claim"
    ]
}

2020-02-14 13:49:14.251126 Step: Verify that cStor pool is h [...]

2020-02-14 16:50 UTC, ksatchit approved these changes

2020-02-14 16:51 UTC, ispeakc0de approved these changes
/lgtm

2020-02-14 16:51 UTC, merged