feat(charts): Adding chaos charts for node-memory-hog experiment
litmuschaos/chaos-charts pull request #163
Opened 2020-03-11 14:48 UTC by uditgaurav

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>

- Adding chaos charts for node-memory-hog experiment

2020-03-11 14:49 UTC, uditgaurav commented
**_Logs with this rbac:_**

```
ansible-playbook 2.7.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
statically imported: /experiments/generic/node_memory_hog/node_memory_hog_ansible_prerequisites.yml

2020-03-11 14:39:27.815805 PLAYBOOK: node_memory_hog_ansible_logic.yml 
1 plays in ./experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml

2020-03-11 14:39:27.837361 ************ BRACE YOURSELF, EXPERIMENT BEGINS! ************ 

2020-03-11 14:39:33.451881 Step: Gathering Facts 
task path: /experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml:2
META: ran handlers

2020-03-11 14:39:33.986221 Step: Identify the chaos util to be invoked 
task path: /experiments/generic/node_memory_hog/node_memory_hog_ansible_prerequisites.yml:1
details => {"changed": true, "checksum": "05311cb7e309713865c76d348dc9ad466dc28e52", "dest": "./chaosutil.yml", "gid": 0, "group": "root", "md5sum": "b2c1b1fb739f6064f372fbe57fbc3af2", "mode": "0644", "owner": "root", "size": 66, "src": "/root/.ansible/tmp/ansible-tmp-1583937573.51-157813942413522/source", "state": "file", "uid": 0}

2020-03-11 14:39:34.040815 Step: include_vars 
task path: /experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml:25
details => {"ansible_facts": {"c_util": "/chaoslib/litmus/platform/gke/node_memory_consumption.yml"}, "ansible_included_var_files": ["/experiments/generic/node_memory_hog/chaosutil.yml"], "changed": false}
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

2020-03-11 14:39:34.456572 Step: Generate the chaos result CR to reflect SOT (Start of Test) 
task path: /utils/runtime/update_chaos_result_resource.yml:3
details => {"changed": true, "checksum": "fb94345cb6cd6667e948944fd59bf2a05e5ee548", "dest": "/utils/runtime/chaos-result.yml", "gid": 0, "group": "root", "md5sum": "88c6dc1e961429854d46f3958fd89d26", "mode": "0644", "owner": "root", "size": 265, "src": "/root/.ansible/tmp/ansible-tmp-1583937574.2-162113440506781/source", "state": "file", "uid": 0}

2020-03-11 14:39:36.090024 Step: Apply the chaos result CR 
task path: /utils/runtime/update_chaos_result_resource.yml:13
details => {"changed": true, "cmd": "kubectl apply -f /utils/runtime/chaos-result.yml -n litmus", "delta": "0:00:01.197954", "end": "2020-03-11 14:39:36.063588", "failed_when_result": false, "rc": 0, "start": "2020-03-11 14:39:34.865634", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/node-memory-hog configured", "stdout_lines": ["chaosresult.litmuschaos.io/node-memory-hog configured"]}
included: /utils/common/status_app_pod.yml for 127.0.0.1

2020-03-11 14:39:37.144506 Step: Checking whether application pods are in running state 
task path: /utils/common/status_app_pod.yml:2
details => {"attempts": 1, "changed": true, "cmd": "kubectl get pods -n litmus -l run=nginx -o custom-columns=:.status.phase --no-headers", "delta": "0:00:00.733543", "end": "2020-03-11 14:39:37.115315", "rc": 0, "start": "2020-03-11 14:39:36.381772", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

2020-03-11 14:39:38.023828 Step: Get the container status of application. 
task path: /utils/common/status_app_pod.yml:9
details => {"attempts": 1, "changed": true, "cmd": "kubectl get pod -n litmus -l run=nginx --no-headers -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | tr ' ' '\\n' | uniq", "delta": "0:00:00.681711", "end": "2020-03-11 14:39:37.992828", "rc": 0, "start": "2020-03-11 14:39:37.311117", "stderr": "", "stderr_lines": [], "stdout": "true", "stdout_lines": ["true"]}
included: /chaoslib/litmus/platform/gke/node_memory_consumption.yml for 127.0.0.1

2020-03-11 14:39:39.163923 Step: Getting the pre-chaos application pod name 
task path: /chaoslib/litmus/platform/gke/node_memory_consumption.yml:4
details => {"changed": false, "resources": [{"apiVersion": "v1", "kind": "Pod", "metadata": {"creationTimestamp": "2020-03-11T14:30:25Z", "generateName": "nginx-7db9fccd9b-", "labels": {"pod-template-hash": "7db9fccd9b", "run": "nginx"}, "name": "nginx-7db9fccd9b-tr9b4", "namespace": "litmus", "ownerReferences": [{"apiVersion": "apps/v1", "blockOwnerDeletion": true, "controller": true, "kind": "ReplicaSet", "name": "nginx-7db9fccd9b", "uid": "d921ba16-63a4-11ea-bb89-42010a80003a"}], "resourceVersion": "356829", "selfLink": "/api/v1/namespaces/litmus/pods/nginx-7db9fccd9b-tr9b4", "uid": "d925ed59-63a4-11ea-bb89-42010a80003a"}, "spec": {"containers": [{"image": "nginx", "imagePullPolicy": "Always", "name": "nginx", "resources": {}, "terminationMessagePath": "/dev/termination-log", "terminationMessagePolicy": "File", "volumeMounts": [{"mountPath": "/var/run/secrets/kubernetes.io/serviceaccount", "name": "default-token-8w2pv", "readOnly": true}]}], "dnsPolicy": "ClusterFirst", "enableServiceLinks": true, "nodeName": "gke-udit-limtus-e2e-default-pool-ec4ec958-3k9b", "priority": 0, "restartPolicy": "Always", "schedulerName": "default-scheduler", "securityContext": {}, "serviceAccount": "default", "serviceAccountName": "default", "terminationGracePeriodSeconds": 30, "tolerations": [{"effect": "NoExecute", "key": "node.kubernetes.io/not-ready", "operator": "Exists", "tolerationSeconds": 300}, {"effect": "NoExecute", "key": "node.kubernetes.io/unreachable", "operator": "Exists", "tolerationSeconds": 300}], "volumes": [{"name": "default-token-8w2pv", "secret": {"defaultMode": 420, "secretName": "default-token-8w2pv"}}]}, "status": {"conditions": [{"lastProbeTime": null, "lastTransitionTime": "2020-03-11T14:30:25Z", "status": "True", "type": "Initialized"}, {"lastProbeTime": null, "lastTransitionTime": "2020-03-11T14:30:27Z", "status": "True", "type": "Ready"}, {"lastProbeTime": null, "lastTransitionTime": "2020-03-11T14:30:27Z", "status": "True", "type": "ContainersReady"}, {"lastProbeTime": null, "lastTransitionTime": "2020-03-11T14:30:25Z", "status": "True", "type": "PodScheduled"}], "containerStatuses": [{"containerID": "docker://8c4110b90eade9d0b7e47b3ef882c96a712d0a758b93ac4f3eaa79813bdd1b55", "image": "nginx:latest", "imageID": "docker-pullable://nginx@sha256:3936fb3946790d711a68c58be93628e43cbca72439079e16d154b5db216b58da", "lastState": {}, "name": "nginx", "ready": true, "restartCount": 0, "state": {"running": {"startedAt": "2020-03-11T14:30:27Z"}}}], "hostIP": "10.128.0.39", "phase": "Running", "podIP": "10.20.1.51", "qosClass": "BestEffort", "startTime": "2020-03-11T14:30:25Z"}}]}

2020-03-11 14:39:39.236147 Step: Recording the node name of application pod 
task path: /chaoslib/litmus/platform/gke/node_memory_consumption.yml:12
details => {"ansible_facts": {"node_name": "gke-udit-limtus-e2e-default-pool-ec4ec958-3k9b"}, "changed": false}

2020-03-11 14:39:40.067503 Step: Generate a run id if not passed from the engine/experiment 
task path: /chaoslib/litmus/platform/gke/node_memory_consumption.yml:17
details => {"changed": true, "cmd": "echo $(mktemp) | cut -d '.' -f 2", "delta": "0:00:00.612802", "end": "2020-03-11 14:39:40.043887", "rc": 0, "start": "2020-03-11 14:39:39.431085", "stderr": "", "stderr_lines": [], "stdout": "lTUvtkH5xU", "stdout_lines": ["lTUvtkH5xU"]}

2020-03-11 14:39:40.131920 Step: set_fact 
task path: /chaoslib/litmus/platform/gke/node_memory_consumption.yml:21
details => {"ansible_facts": {"run_id": "ltuvtkh5xu"}, "changed": false}

2020-03-11 14:39:40.521418 Step: Patch the engine uid 
task path: /chaoslib/litmus/platform/gke/n [...]

2020-03-11 15:53 UTC, ispeakc0de requested changes

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/experiment.yaml
> +  version: 0.0.1
0.1.0

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/experiment.yaml
> +          - "daemonsets"
remove this

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/experiment.yaml
> +      value: ''
pls provide default value

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +  name: node-cpu-hog
node-memory-hog

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +  version: 0.0.1
0.1.0

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    Kubernetes Node memory hog contains chaos to disrupt state of kubernetes resources. Experiments can inject a memory skipe on a node where the application pod is scheduled.
skipe ?

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    - State
node

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    - name: udit
Udit Gaurav

2020-03-11 15:53 UTC, ispeakc0de commented on charts/generic/node-memory-hog/rbac.yaml
> +  resources: ["pods","daemonsets","jobs","pods/log","events","chaosengines","chaosexperiments","chaosresults"]
daemonsets?

2020-03-11 17:24 UTC, ispeakc0de commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    - name: Udit Gaurav
:+1:

2020-03-11 17:25 UTC, ispeakc0de submitted a review, later dismissed
/lgtm

2020-03-12 05:13 UTC, ksatchit commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    - Causes (forced/graceful) Memory hog on a perticular node where the application deployment is available.
there is no such thing as a force/graceful memory hog. Also do a spell check

2020-03-12 05:14 UTC, ksatchit commented on charts/generic/node-memory-hog/node-memory-hog.chartserviceversion.yaml
> +    - After test the recovery should be manual of the application pod and node in case they are not in appropriate state. The chances of such scenarios is when the memory percentance provided is grea
Look at the recovery statement used in CPU hog test

2020-03-12 05:14 UTC, ksatchit requested changes
description changes needed in csv

2020-03-12 06:44 UTC, ispeakc0de commented
@uditgaurav  Can you please add this experiment to package, generic CSV, and an image for this.

2020-03-12 14:34 UTC, ispeakc0de approved these changes
/lgtm

2020-03-12 14:37 UTC, ksatchit approved these changes

2020-03-12 14:37 UTC, merged