feat(charts) add experiment openebs-single-replica-failure
litmuschaos/chaos-charts pull request #23
Opened 2019-10-10 11:10 UTC by shubhamchaudhary

- Add experiment openebs-single-replica-failure

**This PR contains**
- [ ]  experiment.basetemplate.yaml 

- [ ]  chartserviceversion.basetemplate.yaml

**Logs of the executor and job**
[logs-job.txt](https://github.com/litmuschaos/chaos-charts/files/3712095/logs-job.txt)
[logs-executor.txt](https://github.com/litmuschaos/chaos-charts/files/3712096/logs-executor.txt)

2019-10-29 20:40 UTC, chandankumar4 requested changes
Can you add the required permission also for running this experiment

2019-11-26 12:46 UTC, ksatchit commented
@shubhamchaudhary , is the jiva replica failure a separate experiment OR can it be called as a lib from the pool chart?

2019-11-27 20:07 UTC, shubhamchaudhary commented
> @shubhamchaudhary , is the jiva replica failure a separate experiment OR can it be called as a lib from the pool chart?

@ksatchit ,
We can modify our openebs-single-replica-failure experiment so that it will work for both cstor and jiva sc. We can Add lib for both jiva and cstor single replica failure.

2019-12-30 05:23 UTC, chandankumar4 commented on charts/openebs/openebs-single-replica-failure/experiment.yaml
> +spec:
Can we have the permission field also

2019-12-30 05:55 UTC, ksatchit commented
Do we have an experiment in this path Or is the plan to update the pool chaos tests to  work with jiva? @shubhamchaudhary

2019-12-30 16:36 UTC, closed without merging