feat(chart): Add charts for kubelet service kill experiment
litmuschaos/chaos-charts pull request #239
Opened 2020-06-13 09:20 UTC by uditgaurav

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>

- Add charts for kubelet service kill experiment

issue - https://github.com/litmuschaos/litmus/issues/1541

2020-06-13 09:39 UTC, ispeakc0de requested changes

2020-06-13 09:39 UTC, ispeakc0de commented on charts/generic/experiments.yaml
> +apiVersion: litmuschaos.io/v1alpha1
No need to add this manually. This will be automatically added by Travis

2020-06-13 09:39 UTC, ispeakc0de commented on charts/generic/kubelet-service-kill/experiment.yaml
> +    scope: Namespaced
namespaced? or cluster? we are affecting a node right?

2020-06-13 09:39 UTC, ispeakc0de commented on charts/generic/kubelet-service-kill/kubelet-service-kill.chartserviceversion.yaml
> +    - Causes replicas may be evicted or becomes unreachable on account on nodes turning unschedulable (Not Ready) due to kubelet service kill.
turning ? check the typos here

2020-06-13 09:39 UTC, ispeakc0de commented on charts/generic/kubelet-service-kill/rbac.yaml
> +  name: kubelet-service-kill
The separate ns is required?

2020-06-13 09:39 UTC, ispeakc0de commented on charts/generic/kubelet-service-kill/rbac.yaml
> +# Source: openebs/templates/clusterrole.yaml
we can remove this comment

2020-06-13 10:00 UTC, uditgaurav commented on charts/generic/kubelet-service-kill/kubelet-service-kill.chartserviceversion.yaml
> +    - Causes replicas may be evicted or becomes unreachable on account on nodes turning unschedulable (Not Ready) due to kubelet service kill.
turning is not a typo? which typo?

2020-06-13 10:22 UTC, ispeakc0de approved these changes

2020-06-14 13:44 UTC, imrajdas approved these changes
lgtm

2020-06-14 13:45 UTC, merged