chore(docs): Add demo videos in generic chaos experiments
litmuschaos/chaos-charts pull request #257
Opened 2020-07-07 02:03 UTC by Shreyangi

Signed-off-by: Shreyangi <shreyangi.saxena@mayadata.io>

2020-07-07 06:00 UTC, ispeakc0de requested changes

2020-07-07 07:33 UTC, Shreyangi commented on charts/generic/disk-fill/1
> +apiVersion: litmuchaos.io/v1alpha1
I added the video links only, apart from that I didn't changed anything.
Sorry for this but I guess this is a redundant one.

2020-07-07 07:34 UTC, ispeakc0de commented on charts/generic/disk-fill/1
> +apiVersion: litmuchaos.io/v1alpha1
Okay, We can remove this file

2020-07-07 07:36 UTC, Shreyangi commented on charts/generic/disk-fill/1
> +apiVersion: litmuchaos.io/v1alpha1
sorry for the blunder

2020-07-08 07:43 UTC, ispeakc0de approved these changes

2020-07-10 18:32 UTC, uditgaurav approved these changes

2020-07-10 22:52 UTC, merged