Feature(Chart): Chaos charts for Docker Service Kill experiment
litmuschaos/chaos-charts pull request #261
Opened 2020-07-13 15:12 UTC by ghoshankur1983

Signed-off-by: Ankur Ghosh ( ankur.ghosh3@wipro.com)

Adding the Chaos Charts for the Docker Service Kill experiment.

2020-07-13 15:49 UTC, ispeakc0de requested changes

2020-07-13 15:49 UTC, ispeakc0de commented on charts/generic/docker-service-kill/docker-service-kill.chartserviceversion.yaml
> +  keywords: ['pods', 'kubernetes', 'sample-category', 'nginx']
can we remove sample-category?

2020-07-13 15:49 UTC, ispeakc0de commented on charts/generic/docker-service-kill/rbac.yaml
> +  namespace: default
no namespace field required for clusterrole

2020-07-13 15:49 UTC, ispeakc0de commented on charts/generic/docker-service-kill/rbac.yaml
> +  namespace: default
same as above

2020-07-14 07:08 UTC, ghoshankur1983 commented
Incorporated the changes. Please close the pull request if everything is fine.

2020-07-14 07:25 UTC, uditgaurav approved these changes
lgtm

2020-07-14 07:25 UTC, ispeakc0de approved these changes

2020-07-14 07:26 UTC, uditgaurav commented
We can add icons and a Wipro card in upcoming PRs.

2020-07-14 11:07 UTC, merged