(feat): add openebs pool conatiner failure experiment CR
litmuschaos/chaos-charts pull request #39
Opened 2019-11-08 17:56 UTC by shubhamchaudhary

Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

-  modify generic experiments to add lib_image env

- add openebs pool container failure experiment CR

2019-11-11 06:53 UTC, chandankumar4 submitted a review, later dismissed
LGTM

2019-11-11 07:35 UTC, chandankumar4 submitted a review, later dismissed

2019-11-11 07:55 UTC, ksatchit commented on charts/openebs/openebs-pool-container-failure/openebs-pool-container-failure.chartserviceversion.yaml
> +    - Gke
GKE

2019-11-11 13:36 UTC, chandankumar4 submitted a review, later dismissed

2019-11-11 14:27 UTC, ksatchit commented
@shubhamchaudhary can you pls resolve conflicts

2019-11-11 17:34 UTC, chandankumar4 submitted a review, later dismissed

2019-11-12 06:41 UTC, Sanjay1611 requested changes

2019-11-12 06:41 UTC, Sanjay1611 commented on charts/openebs/openebs-pool-container-failure/openebs-pool-container-failure.chartserviceversion.yaml
> +     Kill the pool pod and check if gets scheduled again.
It should be pool container.

2019-11-12 06:41 UTC, Sanjay1611 commented on charts/generic/pod-network-latency/experiment.yaml
> +   - name: NETWORK_LATENCY
Indentation is not right

2019-11-12 06:41 UTC, Sanjay1611 commented on charts/generic/pod-delete/experiment.yaml
> +
no space should be there

2019-11-12 06:41 UTC, Sanjay1611 commented on charts/openebs/openebs-pool-container-failure/experiment.yaml
> +    Kill the pool pod and check if gets scheduled again
pool `container`

2019-11-12 19:42 UTC, chandankumar4 approved these changes

2019-11-12 19:43 UTC, ksatchit approved these changes

2019-11-12 19:43 UTC, merged