Adding aws az experiment charts
litmuschaos/chaos-charts pull request #542
Opened 2022-04-23 18:38 UTC by oumkale

Signed-off-by: oumkale <oumkale@chaosnative.com>
- Adding aws az experiment charts

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/aws-az-chaos.chartserviceversion.yaml
> +    - "sample-category"
can we remove this sample-category?

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/aws-az-chaos.chartserviceversion.yaml
> +    - "exec"
we can also remove exec instead we can use keywords like AWS, Availability Zone,

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/engine.yaml
> +  jobCleanUpPolicy: 'delete'
can we remove jobCleanUpPolicy from here? We are using default values now (as retain)?

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/engine.yaml
> +              value: "na"
what is `na` mean here? can we keep it default and explain the variable role in a comment (one liner comment, you can also do this in experiment.yml)

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/rbac.yaml
> +metadata:
can you refer to the RBAC from AWS or any other infra chaos experiment and provide the minimum role?

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/experiment.yaml
> +      value: ''
litmus we can fill in the lib

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/rbac.yaml
> +      - "pods/exec"
pls check if we need some of this permission as we don't `pods/exec`?

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az.chartserviceversion.yaml
> +    Execute AWS AZ failure Chaos on given regions
can we check the description - it will be visible on the chaos hub.

2022-04-26 11:11 UTC, uditgaurav commented on charts/aws-az/aws-az.chartserviceversion.yaml
> +    - "exec"
pls check these

2022-05-12 15:16 UTC, oumkale commented on charts/aws-az/aws-az-chaos/engine.yaml
> +              value: "na"
Yes we can update that in experiment, for now let it be in engine and experiment file.
This env is to specify a resource in a policy statement @uditgaurav

2022-05-13 06:21 UTC, avaakash requested changes

2022-05-13 06:21 UTC, avaakash commented on charts/aws-az/aws-az-chaos/aws-az-chaos.chartserviceversion.yaml
> +    Execute aws-az chaos to detach the target zones from loa balancer
```suggestion
    Execute aws-az chaos to detach the target zones from a load balancer
```

2022-05-13 06:21 UTC, avaakash commented on charts/aws-az/aws-az-chaos/engine.yaml
> +  auxiliaryAppInfo: ''
There is no check for aux app in the experiment, so we can remove this
```suggestion
  auxiliaryAppInfo: ''
```

2022-05-31 18:05 UTC, avaakash commented
Hi @oumkale can you resolve conflicts with master branch and also fix DCO failing.

2022-06-14 07:04 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/engine.yaml
> +  chaosServiceAccount: litmus-admin
```suggestion
  chaosServiceAccount: aws-az-chaos-sa
```

2022-06-14 07:06 UTC, uditgaurav approved these changes, later dismissed

2022-06-14 07:09 UTC, uditgaurav commented on charts/aws-az/aws-az-chaos/experiment.yaml
> +      value: ''
```suggestion
    - name: TOTAL_CHAOS_DURATION
      value: '30'
    - name: CHAOS_INTERVAL
      value: '30'
    - name: LIB
      value: 'litmus'
```

2022-06-14 07:10 UTC, uditgaurav submitted a review, later dismissed

2022-06-14 07:11 UTC, avaakash approved these changes, later dismissed

2022-06-14 07:53 UTC, uditgaurav submitted a review, later dismissed

2022-06-14 08:01 UTC, neelanjan00 commented on charts/kube-aws/kube-aws.chartserviceversion.yaml
>      - EBS
Can we also include AZ here?

2022-06-14 08:13 UTC, oumkale commented on charts/kube-aws/kube-aws.chartserviceversion.yaml
>      - EBS
Done

2022-06-14 08:32 UTC, avaakash approved these changes

2022-06-14 08:37 UTC, neelanjan00 approved these changes

2022-06-14 10:02 UTC, uditgaurav approved these changes

2022-06-14 10:02 UTC, merged