Updates GCP VM Instance Stop by Label experiment chart
litmuschaos/chaos-charts pull request #548
Opened 2022-05-16 08:27 UTC by neelanjan00

-Updates gcp-vm-instance-stop-by-label experiment chartserviceversion and experiment charts

2022-05-16 12:33 UTC, avaakash requested changes

2022-05-16 12:33 UTC, avaakash commented on charts/gcp/gcp-vm-instance-stop-by-label/experiment.yaml
> +    Stops GCP VM instances and GKE nodes filtered by a label for a specified duration of time and later restarts them
```suggestion
    Stops GCP VM instances and GKE nodes filtered by a label for a specified duration and later restarts them 
```
duration means time

2022-05-16 12:33 UTC, avaakash commented on charts/gcp/gcp-vm-instance-stop-by-label/gcp-vm-instance-stop-by-label.chartserviceversion.yaml
>      Stops GCP VM instances and GKE nodes filtered by a label for a specified duration of time and later restarts them
```suggestion
    Stops GCP VM instances and GKE nodes filtered by a label for a specified duration and later restarts them 
```

2022-05-16 17:32 UTC, avaakash approved these changes, later dismissed

2022-05-26 20:00 UTC, avaakash approved these changes

2022-06-02 09:45 UTC, uditgaurav approved these changes

2022-06-02 09:46 UTC, merged